services:
    partfire_common.repo:
        class: PartFire\CommonBundle\Entity\Repository\RepositoryFactory
        arguments: ['@doctrine.orm.default_entity_manager']

    partfire_common.country_repository:
        class: Doctrine\ORM\EntityRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - PartFire\CommonBundle\Entity\Country

    partfire_common.output_burn:
        class: PartFire\CommonBundle\Services\Output\Cli\BurnOutput

    partfire_common.output_console:
        class: PartFire\CommonBundle\Services\Output\Cli\ConsoleOutput
